import type { Surah } from './types'

// Bundled fallback list of all 114 surahs (UmmahAPI shape).
// Used only if the live API is unreachable so the UI never blocks.
export const SURAHS_FALLBACK: Surah[] = [
  { number: 1, name: 'Al-Fatihah', englishName: 'The Opening', arabicName: 'الفاتحة', numberOfAyahs: 7, revelationType: 'Meccan' },
  { number: 2, name: 'Al-Baqarah', englishName: 'The Cow', arabicName: 'البقرة', numberOfAyahs: 286, revelationType: 'Medinan' },
  { number: 3, name: 'Aal-E-Imran', englishName: 'The Family of Imran', arabicName: 'آل عمران', numberOfAyahs: 200, revelationType: 'Medinan' },
  { number: 4, name: 'An-Nisa', englishName: 'The Women', arabicName: 'النساء', numberOfAyahs: 176, revelationType: 'Medinan' },
  { number: 5, name: 'Al-Maidah', englishName: 'The Table Spread', arabicName: 'المائدة', numberOfAyahs: 120, revelationType: 'Medinan' },
  { number: 6, name: 'Al-Anam', englishName: 'The Cattle', arabicName: 'الأنعام', numberOfAyahs: 165, revelationType: 'Meccan' },
  { number: 7, name: 'Al-Araf', englishName: 'The Heights', arabicName: 'الأعراف', numberOfAyahs: 206, revelationType: 'Meccan' },
  { number: 8, name: 'Al-Anfal', englishName: 'The Spoils of War', arabicName: 'الأنفال', numberOfAyahs: 75, revelationType: 'Medinan' },
  { number: 9, name: 'At-Tawbah', englishName: 'The Repentance', arabicName: 'التوبة', numberOfAyahs: 129, revelationType: 'Medinan' },
  { number: 10, name: 'Yunus', englishName: 'Jonah', arabicName: 'يونس', numberOfAyahs: 109, revelationType: 'Meccan' },
  { number: 11, name: 'Hud', englishName: 'Hud', arabicName: 'هود', numberOfAyahs: 123, revelationType: 'Meccan' },
  { number: 12, name: 'Yusuf', englishName: 'Joseph', arabicName: 'يوسف', numberOfAyahs: 111, revelationType: 'Meccan' },
  { number: 13, name: 'Ar-Rad', englishName: 'The Thunder', arabicName: 'الرعد', numberOfAyahs: 43, revelationType: 'Medinan' },
  { number: 14, name: 'Ibrahim', englishName: 'Abraham', arabicName: 'إبراهيم', numberOfAyahs: 52, revelationType: 'Meccan' },
  { number: 15, name: 'Al-Hijr', englishName: 'The Rocky Tract', arabicName: 'الحجر', numberOfAyahs: 99, revelationType: 'Meccan' },
  { number: 16, name: 'An-Nahl', englishName: 'The Bee', arabicName: 'النحل', numberOfAyahs: 128, revelationType: 'Meccan' },
  { number: 17, name: 'Al-Isra', englishName: 'The Night Journey', arabicName: 'الإسراء', numberOfAyahs: 111, revelationType: 'Meccan' },
  { number: 18, name: 'Al-Kahf', englishName: 'The Cave', arabicName: 'الكهف', numberOfAyahs: 110, revelationType: 'Meccan' },
  { number: 19, name: 'Maryam', englishName: 'Mary', arabicName: 'مريم', numberOfAyahs: 98, revelationType: 'Meccan' },
  { number: 20, name: 'Ta-Ha', englishName: 'Ta-Ha', arabicName: 'طه', numberOfAyahs: 135, revelationType: 'Meccan' },
  { number: 21, name: 'Al-Anbiya', englishName: 'The Prophets', arabicName: 'الأنبياء', numberOfAyahs: 112, revelationType: 'Meccan' },
  { number: 22, name: 'Al-Hajj', englishName: 'The Pilgrimage', arabicName: 'الحج', numberOfAyahs: 78, revelationType: 'Medinan' },
  { number: 23, name: 'Al-Muminun', englishName: 'The Believers', arabicName: 'المؤمنون', numberOfAyahs: 118, revelationType: 'Meccan' },
  { number: 24, name: 'An-Nur', englishName: 'The Light', arabicName: 'النور', numberOfAyahs: 64, revelationType: 'Medinan' },
  { number: 25, name: 'Al-Furqan', englishName: 'The Criterion', arabicName: 'الفرقان', numberOfAyahs: 77, revelationType: 'Meccan' },
  { number: 26, name: 'Ash-Shuara', englishName: 'The Poets', arabicName: 'الشعراء', numberOfAyahs: 227, revelationType: 'Meccan' },
  { number: 27, name: 'An-Naml', englishName: 'The Ant', arabicName: 'النمل', numberOfAyahs: 93, revelationType: 'Meccan' },
  { number: 28, name: 'Al-Qasas', englishName: 'The Stories', arabicName: 'القصص', numberOfAyahs: 88, revelationType: 'Meccan' },
  { number: 29, name: 'Al-Ankabut', englishName: 'The Spider', arabicName: 'العنكبوت', numberOfAyahs: 69, revelationType: 'Meccan' },
  { number: 30, name: 'Ar-Rum', englishName: 'The Romans', arabicName: 'الروم', numberOfAyahs: 60, revelationType: 'Meccan' },
  { number: 31, name: 'Luqman', englishName: 'Luqman', arabicName: 'لقمان', numberOfAyahs: 34, revelationType: 'Meccan' },
  { number: 32, name: 'As-Sajdah', englishName: 'The Prostration', arabicName: 'السجدة', numberOfAyahs: 30, revelationType: 'Meccan' },
  { number: 33, name: 'Al-Ahzab', englishName: 'The Combined Forces', arabicName: 'الأحزاب', numberOfAyahs: 73, revelationType: 'Medinan' },
  { number: 34, name: 'Saba', englishName: 'Sheba', arabicName: 'سبأ', numberOfAyahs: 54, revelationType: 'Meccan' },
  { number: 35, name: 'Fatir', englishName: 'Originator', arabicName: 'فاطر', numberOfAyahs: 45, revelationType: 'Meccan' },
  { number: 36, name: 'Ya-Sin', englishName: 'Ya Sin', arabicName: 'يس', numberOfAyahs: 83, revelationType: 'Meccan' },
  { number: 37, name: 'As-Saffat', englishName: 'Those who set the Ranks', arabicName: 'الصافات', numberOfAyahs: 182, revelationType: 'Meccan' },
  { number: 38, name: 'Sad', englishName: 'The Letter Saad', arabicName: 'ص', numberOfAyahs: 88, revelationType: 'Meccan' },
  { number: 39, name: 'Az-Zumar', englishName: 'The Troops', arabicName: 'الزمر', numberOfAyahs: 75, revelationType: 'Meccan' },
  { number: 40, name: 'Ghafir', englishName: 'The Forgiver', arabicName: 'غافر', numberOfAyahs: 85, revelationType: 'Meccan' },
  { number: 41, name: 'Fussilat', englishName: 'Explained in Detail', arabicName: 'فصلت', numberOfAyahs: 54, revelationType: 'Meccan' },
  { number: 42, name: 'Ash-Shura', englishName: 'The Consultation', arabicName: 'الشورى', numberOfAyahs: 53, revelationType: 'Meccan' },
  { number: 43, name: 'Az-Zukhruf', englishName: 'The Ornaments of Gold', arabicName: 'الزخرف', numberOfAyahs: 89, revelationType: 'Meccan' },
  { number: 44, name: 'Ad-Dukhan', englishName: 'The Smoke', arabicName: 'الدخان', numberOfAyahs: 59, revelationType: 'Meccan' },
  { number: 45, name: 'Al-Jathiyah', englishName: 'The Crouching', arabicName: 'الجاثية', numberOfAyahs: 37, revelationType: 'Meccan' },
  { number: 46, name: 'Al-Ahqaf', englishName: 'The Wind-Curved Sandhills', arabicName: 'الأحقاف', numberOfAyahs: 35, revelationType: 'Meccan' },
  { number: 47, name: 'Muhammad', englishName: 'Muhammad', arabicName: 'محمد', numberOfAyahs: 38, revelationType: 'Medinan' },
  { number: 48, name: 'Al-Fath', englishName: 'The Victory', arabicName: 'الفتح', numberOfAyahs: 29, revelationType: 'Medinan' },
  { number: 49, name: 'Al-Hujurat', englishName: 'The Rooms', arabicName: 'الحجرات', numberOfAyahs: 18, revelationType: 'Medinan' },
  { number: 50, name: 'Qaf', englishName: 'The Letter Qaf', arabicName: 'ق', numberOfAyahs: 45, revelationType: 'Meccan' },
  { number: 51, name: 'Adh-Dhariyat', englishName: 'The Winnowing Winds', arabicName: 'الذاريات', numberOfAyahs: 60, revelationType: 'Meccan' },
  { number: 52, name: 'At-Tur', englishName: 'The Mount', arabicName: 'الطور', numberOfAyahs: 49, revelationType: 'Meccan' },
  { number: 53, name: 'An-Najm', englishName: 'The Star', arabicName: 'النجم', numberOfAyahs: 62, revelationType: 'Meccan' },
  { number: 54, name: 'Al-Qamar', englishName: 'The Moon', arabicName: 'القمر', numberOfAyahs: 55, revelationType: 'Meccan' },
  { number: 55, name: 'Ar-Rahman', englishName: 'The Beneficent', arabicName: 'الرحمن', numberOfAyahs: 78, revelationType: 'Medinan' },
  { number: 56, name: 'Al-Waqiah', englishName: 'The Inevitable', arabicName: 'الواقعة', numberOfAyahs: 96, revelationType: 'Meccan' },
  { number: 57, name: 'Al-Hadid', englishName: 'The Iron', arabicName: 'الحديد', numberOfAyahs: 29, revelationType: 'Medinan' },
  { number: 58, name: 'Al-Mujadila', englishName: 'The Pleading Woman', arabicName: 'المجادلة', numberOfAyahs: 22, revelationType: 'Medinan' },
  { number: 59, name: 'Al-Hashr', englishName: 'The Exile', arabicName: 'الحشر', numberOfAyahs: 24, revelationType: 'Medinan' },
  { number: 60, name: 'Al-Mumtahanah', englishName: 'She that is to be examined', arabicName: 'الممتحنة', numberOfAyahs: 13, revelationType: 'Medinan' },
  { number: 61, name: 'As-Saff', englishName: 'The Ranks', arabicName: 'الصف', numberOfAyahs: 14, revelationType: 'Medinan' },
  { number: 62, name: 'Al-Jumuah', englishName: 'The Congregation, Friday', arabicName: 'الجمعة', numberOfAyahs: 11, revelationType: 'Medinan' },
  { number: 63, name: 'Al-Munafiqun', englishName: 'The Hypocrites', arabicName: 'المنافقون', numberOfAyahs: 11, revelationType: 'Medinan' },
  { number: 64, name: 'At-Taghabun', englishName: 'The Mutual Disillusion', arabicName: 'التغابن', numberOfAyahs: 18, revelationType: 'Medinan' },
  { number: 65, name: 'At-Talaq', englishName: 'The Divorce', arabicName: 'الطلاق', numberOfAyahs: 12, revelationType: 'Medinan' },
  { number: 66, name: 'At-Tahrim', englishName: 'The Prohibition', arabicName: 'التحريم', numberOfAyahs: 12, revelationType: 'Medinan' },
  { number: 67, name: 'Al-Mulk', englishName: 'The Sovereignty', arabicName: 'الملك', numberOfAyahs: 30, revelationType: 'Meccan' },
  { number: 68, name: 'Al-Qalam', englishName: 'The Pen', arabicName: 'القلم', numberOfAyahs: 52, revelationType: 'Meccan' },
  { number: 69, name: 'Al-Haqqah', englishName: 'The Reality', arabicName: 'الحاقة', numberOfAyahs: 52, revelationType: 'Meccan' },
  { number: 70, name: 'Al-Maarij', englishName: 'The Ascending Stairways', arabicName: 'المعارج', numberOfAyahs: 44, revelationType: 'Meccan' },
  { number: 71, name: 'Nuh', englishName: 'Noah', arabicName: 'نوح', numberOfAyahs: 28, revelationType: 'Meccan' },
  { number: 72, name: 'Al-Jinn', englishName: 'The Jinn', arabicName: 'الجن', numberOfAyahs: 28, revelationType: 'Meccan' },
  { number: 73, name: 'Al-Muzzammil', englishName: 'The Enshrouded One', arabicName: 'المزمل', numberOfAyahs: 20, revelationType: 'Meccan' },
  { number: 74, name: 'Al-Muddaththir', englishName: 'The Cloaked One', arabicName: 'المدثر', numberOfAyahs: 56, revelationType: 'Meccan' },
  { number: 75, name: 'Al-Qiyamah', englishName: 'The Resurrection', arabicName: 'القيامة', numberOfAyahs: 40, revelationType: 'Meccan' },
  { number: 76, name: 'Al-Insan', englishName: 'Man', arabicName: 'الإنسان', numberOfAyahs: 31, revelationType: 'Medinan' },
  { number: 77, name: 'Al-Mursalat', englishName: 'The Emissaries', arabicName: 'المرسلات', numberOfAyahs: 50, revelationType: 'Meccan' },
  { number: 78, name: 'An-Naba', englishName: 'The Tidings', arabicName: 'النبأ', numberOfAyahs: 40, revelationType: 'Meccan' },
  { number: 79, name: 'An-Naziat', englishName: 'Those who drag forth', arabicName: 'النازعات', numberOfAyahs: 46, revelationType: 'Meccan' },
  { number: 80, name: 'Abasa', englishName: 'He Frowned', arabicName: 'عبس', numberOfAyahs: 42, revelationType: 'Meccan' },
  { number: 81, name: 'At-Takwir', englishName: 'The Overthrowing', arabicName: 'التكوير', numberOfAyahs: 29, revelationType: 'Meccan' },
  { number: 82, name: 'Al-Infitar', englishName: 'The Cleaving', arabicName: 'الإنفطار', numberOfAyahs: 19, revelationType: 'Meccan' },
  { number: 83, name: 'Al-Mutaffifin', englishName: 'The Defrauding', arabicName: 'المطففين', numberOfAyahs: 36, revelationType: 'Meccan' },
  { number: 84, name: 'Al-Inshiqaq', englishName: 'The Sundering', arabicName: 'الإنشقاق', numberOfAyahs: 25, revelationType: 'Meccan' },
  { number: 85, name: 'Al-Buruj', englishName: 'The Mansions of the Stars', arabicName: 'البروج', numberOfAyahs: 22, revelationType: 'Meccan' },
  { number: 86, name: 'At-Tariq', englishName: 'The Morning Star', arabicName: 'الطارق', numberOfAyahs: 17, revelationType: 'Meccan' },
  { number: 87, name: 'Al-Ala', englishName: 'The Most High', arabicName: 'الأعلى', numberOfAyahs: 19, revelationType: 'Meccan' },
  { number: 88, name: 'Al-Ghashiyah', englishName: 'The Overwhelming', arabicName: 'الغاشية', numberOfAyahs: 26, revelationType: 'Meccan' },
  { number: 89, name: 'Al-Fajr', englishName: 'The Dawn', arabicName: 'الفجر', numberOfAyahs: 30, revelationType: 'Meccan' },
  { number: 90, name: 'Al-Balad', englishName: 'The City', arabicName: 'البلد', numberOfAyahs: 20, revelationType: 'Meccan' },
  { number: 91, name: 'Ash-Shams', englishName: 'The Sun', arabicName: 'الشمس', numberOfAyahs: 15, revelationType: 'Meccan' },
  { number: 92, name: 'Al-Layl', englishName: 'The Night', arabicName: 'الليل', numberOfAyahs: 21, revelationType: 'Meccan' },
  { number: 93, name: 'Ad-Duha', englishName: 'The Morning Hours', arabicName: 'الضحى', numberOfAyahs: 11, revelationType: 'Meccan' },
  { number: 94, name: 'Ash-Sharh', englishName: 'The Relief', arabicName: 'الشرح', numberOfAyahs: 8, revelationType: 'Meccan' },
  { number: 95, name: 'At-Tin', englishName: 'The Fig', arabicName: 'التين', numberOfAyahs: 8, revelationType: 'Meccan' },
  { number: 96, name: 'Al-Alaq', englishName: 'The Clot', arabicName: 'العلق', numberOfAyahs: 19, revelationType: 'Meccan' },
  { number: 97, name: 'Al-Qadr', englishName: 'The Power', arabicName: 'القدر', numberOfAyahs: 5, revelationType: 'Meccan' },
  { number: 98, name: 'Al-Bayyinah', englishName: 'The Clear Proof', arabicName: 'البينة', numberOfAyahs: 8, revelationType: 'Medinan' },
  { number: 99, name: 'Az-Zalzalah', englishName: 'The Earthquake', arabicName: 'الزلزلة', numberOfAyahs: 8, revelationType: 'Medinan' },
  { number: 100, name: 'Al-Adiyat', englishName: 'The Courser', arabicName: 'العاديات', numberOfAyahs: 11, revelationType: 'Meccan' },
  { number: 101, name: 'Al-Qariah', englishName: 'The Calamity', arabicName: 'القارعة', numberOfAyahs: 11, revelationType: 'Meccan' },
  { number: 102, name: 'At-Takathur', englishName: 'The Rivalry in world increase', arabicName: 'التكاثر', numberOfAyahs: 8, revelationType: 'Meccan' },
  { number: 103, name: 'Al-Asr', englishName: 'The Declining Day', arabicName: 'العصر', numberOfAyahs: 3, revelationType: 'Meccan' },
  { number: 104, name: 'Al-Humazah', englishName: 'The Traducer', arabicName: 'الهمزة', numberOfAyahs: 9, revelationType: 'Meccan' },
  { number: 105, name: 'Al-Fil', englishName: 'The Elephant', arabicName: 'الفيل', numberOfAyahs: 5, revelationType: 'Meccan' },
  { number: 106, name: 'Quraysh', englishName: 'Quraysh', arabicName: 'قريش', numberOfAyahs: 4, revelationType: 'Meccan' },
  { number: 107, name: 'Al-Maun', englishName: 'The Small Kindnesses', arabicName: 'الماعون', numberOfAyahs: 7, revelationType: 'Meccan' },
  { number: 108, name: 'Al-Kawthar', englishName: 'The Abundance', arabicName: 'الكوثر', numberOfAyahs: 3, revelationType: 'Meccan' },
  { number: 109, name: 'Al-Kafirun', englishName: 'The Disbelievers', arabicName: 'الكافرون', numberOfAyahs: 6, revelationType: 'Meccan' },
  { number: 110, name: 'An-Nasr', englishName: 'The Divine Support', arabicName: 'النصر', numberOfAyahs: 3, revelationType: 'Medinan' },
  { number: 111, name: 'Al-Masad', englishName: 'The Palm Fiber', arabicName: 'المسد', numberOfAyahs: 5, revelationType: 'Meccan' },
  { number: 112, name: 'Al-Ikhlas', englishName: 'The Sincerity', arabicName: 'الإخلاص', numberOfAyahs: 4, revelationType: 'Meccan' },
  { number: 113, name: 'Al-Falaq', englishName: 'The Daybreak', arabicName: 'الفلق', numberOfAyahs: 5, revelationType: 'Meccan' },
  { number: 114, name: 'An-Nas', englishName: 'Mankind', arabicName: 'الناس', numberOfAyahs: 6, revelationType: 'Meccan' },
]
